__author__ = 'igor rocha'

"""
    Problem 2 - Even Fibonacci numbers

    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
    the first 10 terms will be:

        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
    even-valued terms.
"""

MAX = 4000000


def fibonacci():
    fib = [0, 1]
    while True:
        proximo = fib[-1] + fib[-2]
        if proximo > MAX: return
        fib.append(proximo)
        yield proximo


print(sum(filter(lambda x: x % 2 == 0, fibonacci())))